######################################################################
# Automatically generated by qmake (2.01a) ?? 9? 16 22:33:40 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += detailset.h display.h speed.h
SOURCES += detailset.cpp display.cpp displayfunction.cpp main.cpp speed.cpp
RESOURCES += resource.qrc
